package br.ufmt.ic.alg3.viks.view;

import br.ufmt.ic.alg3.viks.view.tableModel.HabilidadesTableModel;
import br.ufmt.ic.alg3.viks.model.entidades.Habilidades;
import br.ufmt.ic.alg3.viks.persistencia.HabilidadesPersistencia;
import br.ufmt.ic.alg3.viks.persistencia.MySQL.HabilidadePersistenciaMySQL;
import br.ufmt.ic.alg3.viks.persistencia.arquivo.HabilidadesPersistenciaArquivo;
import javax.swing.JOptionPane;

public class HabilidadesJPanel extends javax.swing.JPanel {

    private final HabilidadesPersistencia banco = new HabilidadePersistenciaMySQL();
    private final HabilidadesTableModel tableModel;
    
    /**
     * Creates new form HabilidadesJPanel
     */
    public HabilidadesJPanel() {
        tableModel = new HabilidadesTableModel(banco.getAll());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        xpjLabel = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        utilidadejLabel = new javax.swing.JLabel();
        utilidadejTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        xpjTextField = new javax.swing.JTextField();
        idjTextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        idjLabel.setText("Id:");

        xpjLabel.setText("XP:");

        nomejLabel.setText("Nome:");

        utilidadejLabel.setText("Utilidade:");

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        idjTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerjButton)
                    .addComponent(editarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(salvarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(utilidadejLabel)
                            .addComponent(nomejLabel)
                            .addComponent(xpjLabel)
                            .addComponent(idjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(utilidadejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                            .addComponent(xpjTextField)
                            .addComponent(nomejTextField)
                            .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xpjLabel)
                    .addComponent(xpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utilidadejLabel)
                    .addComponent(utilidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(cancelarjButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(removerjButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        float convertido;
        Habilidades novo = new Habilidades();
        novo.setNome(nomejTextField.getText());
        novo.setUtilidade(utilidadejTextField.getText());
        convertido = Float.parseFloat(xpjTextField.getText());
        novo.setXp(convertido);

        int id = 0;
        try {
            id = Integer.parseInt(idjTextField.getText());
            novo.setId(id);
            banco.alterar(novo);
        } catch (Exception erro) {
            banco.inserir(novo);
        }

        JOptionPane.showMessageDialog(
                salvarjButton, "Salvo com Sucesso!");

        cancelarjButtonActionPerformed(null);

        HabilidadesTableModel modelo
                = (HabilidadesTableModel) tabelajTable.getModel();

        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idjTextField.setText("");
        xpjTextField.setText("");
        nomejTextField.setText("");
        utilidadejTextField.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();

        for (int i = linhas.length - 1; i >= 0; i--) {
            Habilidades removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);

            HabilidadesTableModel modelo
                    = (HabilidadesTableModel) tabelajTable.getModel();

            modelo.fireTableRowsDeleted(0, 1);
        }
    }//GEN-LAST:event_removerjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int linha = tabelajTable.getSelectedRow();

        if (linha >= 0) {
            Habilidades selecionado;
            float convertido;
            selecionado = banco.getAll().get(linha);

            idjTextField.setText(selecionado.getId() + "");
            nomejTextField.setText(selecionado.getNome());
            utilidadejTextField.setText(selecionado.getUtilidade());
            xpjTextField.setText(selecionado.getXp()+"");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione 1 registro");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed
                                                                                                                                                                             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton removerjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    private javax.swing.JLabel utilidadejLabel;
    private javax.swing.JTextField utilidadejTextField;
    private javax.swing.JLabel xpjLabel;
    private javax.swing.JTextField xpjTextField;
    // End of variables declaration//GEN-END:variables
}
