package br.ufmt.ic.alg3.viks.view;

import br.ufmt.ic.alg3.viks.view.tableModel.HistoriaTableModel;
import br.ufmt.ic.alg3.viks.model.entidades.Historia;
import br.ufmt.ic.alg3.viks.persistencia.HistoriaPersistencia;
import br.ufmt.ic.alg3.viks.persistencia.MySQL.HistoriaPersistenciaMySQL;
import br.ufmt.ic.alg3.viks.persistencia.arquivo.HistoriaPersistenciaArquivo;
import javax.swing.JOptionPane;

public class HistoriaJPanel extends javax.swing.JPanel {

    private final HistoriaPersistencia banco = new HistoriaPersistenciaMySQL();
    private final HistoriaTableModel tableModel;
    
    /**
     * Creates new form HistoriaJPanel
     */
    public HistoriaJPanel() {
        tableModel = new HistoriaTableModel(banco.getAll());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        narracaojLabel = new javax.swing.JLabel();
        titulojLabel = new javax.swing.JLabel();
        titulojTextField = new javax.swing.JTextField();
        dialogojLabel = new javax.swing.JLabel();
        dialogojTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        narracaojTextField = new javax.swing.JTextField();
        idjTextField = new javax.swing.JTextField();
        roteirojLabel = new javax.swing.JLabel();
        roteirojTextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        idjLabel.setText("Id:");

        narracaojLabel.setText("Narração:");

        titulojLabel.setText("Titulo:");

        titulojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulojTextFieldActionPerformed(evt);
            }
        });

        dialogojLabel.setText("Dialogo:");

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        idjTextField.setEditable(false);

        roteirojLabel.setText("Roteiro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(salvarjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelarjButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dialogojLabel)
                                    .addComponent(titulojLabel)
                                    .addComponent(narracaojLabel)
                                    .addComponent(idjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dialogojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                                    .addComponent(narracaojTextField)
                                    .addComponent(titulojTextField)
                                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(removerjButton)
                                    .addComponent(editarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roteirojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roteirojTextField)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulojLabel)
                    .addComponent(titulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(narracaojLabel)
                    .addComponent(narracaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogojLabel)
                    .addComponent(dialogojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roteirojLabel)
                    .addComponent(roteirojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(cancelarjButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removerjButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        float convertido;
        Historia novo = new Historia();
        novo.setTitulo(titulojTextField.getText());
        novo.setNarracao(narracaojTextField.getText());
        novo.setDialogo(dialogojTextField.getText());
        novo.setRoteiro(roteirojTextField.getText());
        

        int id = 0;
        try {
            id = Integer.parseInt(idjTextField.getText());
            novo.setId(id);
            banco.alterar(novo);
        } catch (Exception erro) {
            banco.inserir(novo);
        }

        JOptionPane.showMessageDialog(
                salvarjButton, "Salvo com Sucesso!");

        cancelarjButtonActionPerformed(null);

        HistoriaTableModel modelo
                = (HistoriaTableModel) tabelajTable.getModel();

        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idjTextField.setText("");
        titulojTextField.setText("");
        narracaojTextField.setText("");
        dialogojTextField.setText("");
        roteirojTextField.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();

        for (int i = linhas.length - 1; i >= 0; i--) {
            Historia removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);

            HistoriaTableModel modelo
                    = (HistoriaTableModel) tabelajTable.getModel();

            modelo.fireTableRowsDeleted(0, 1);
        }
    }//GEN-LAST:event_removerjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int linha = tabelajTable.getSelectedRow();

        if (linha >= 0) {
            Historia selecionado;
            float convertido;
            selecionado = banco.getAll().get(linha);

            idjTextField.setText(selecionado.getId() + "");
            titulojTextField.setText(selecionado.getTitulo());
            narracaojTextField.setText(selecionado.getNarracao());
            dialogojTextField.setText(selecionado.getDialogo());
            roteirojTextField.setText(selecionado.getRoteiro());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione 1 registro");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void titulojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulojTextFieldActionPerformed
                                                                                                                                                                             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JLabel dialogojLabel;
    private javax.swing.JTextField dialogojTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel narracaojLabel;
    private javax.swing.JTextField narracaojTextField;
    private javax.swing.JButton removerjButton;
    private javax.swing.JLabel roteirojLabel;
    private javax.swing.JTextField roteirojTextField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JTextField titulojTextField;
    // End of variables declaration//GEN-END:variables
}
