package br.ufmt.ic.alg3.viks.view;

import br.ufmt.ic.alg3.viks.view.tableModel.PersonagemTableModel;
import br.ufmt.ic.alg3.viks.model.entidades.Personagem;
import br.ufmt.ic.alg3.viks.persistencia.PersonagemPersistencia;
import br.ufmt.ic.alg3.viks.persistencia.MySQL.PersonagemPersistenciaMySQL;
import javax.swing.JOptionPane;

public class PersonagemJPanel extends javax.swing.JPanel {

    private final PersonagemPersistencia banco = new PersonagemPersistenciaMySQL();
    private final PersonagemTableModel tableModel;
    
    /**
     * Creates new form PersonagemJPanel
     */
    public PersonagemJPanel() {
        tableModel = new PersonagemTableModel(banco.getAll());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        hpjLabel = new javax.swing.JLabel();
        adrenjLabel = new javax.swing.JLabel();
        adrenjTextField = new javax.swing.JTextField();
        inventariojLabel = new javax.swing.JLabel();
        inventariojTextField = new javax.swing.JTextField();
        cenariojLabel = new javax.swing.JLabel();
        cenariojTextField = new javax.swing.JTextField();
        equipamentosjLabel = new javax.swing.JLabel();
        equipamentosjTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        hpjTextField = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        idjTextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        idjLabel.setText("Id:");

        nomejLabel.setText("Nome:");

        hpjLabel.setText("HP:");

        adrenjLabel.setText("Adrenalina:");

        inventariojLabel.setText("Inventario:");

        inventariojTextField.setEditable(false);

        cenariojLabel.setText("Cenario:");

        cenariojTextField.setEditable(false);

        equipamentosjLabel.setText("Equipamentos:");

        equipamentosjTextField.setEditable(false);

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        tabelajTable.setModel(tableModel);
        jScrollPane1.setViewportView(tabelajTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        idjTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(equipamentosjLabel)
                            .addComponent(cenariojLabel)
                            .addComponent(inventariojLabel)
                            .addComponent(adrenjLabel)
                            .addComponent(hpjLabel)
                            .addComponent(nomejLabel)
                            .addComponent(idjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salvarjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelarjButton))
                            .addComponent(adrenjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                            .addComponent(inventariojTextField)
                            .addComponent(equipamentosjTextField)
                            .addComponent(cenariojTextField)
                            .addComponent(nomejTextField)
                            .addComponent(hpjTextField)
                            .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpjLabel)
                    .addComponent(hpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adrenjLabel)
                    .addComponent(adrenjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventariojLabel)
                    .addComponent(inventariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cenariojLabel)
                    .addComponent(cenariojTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equipamentosjLabel)
                    .addComponent(equipamentosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(cancelarjButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(removerjButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarjButton)
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        int convertido;
        Personagem novo = new Personagem();
        novo.setNome(nomejTextField.getText());
        convertido = Integer.parseInt(hpjTextField.getText());
        novo.setHp(convertido);
        convertido = Integer.parseInt(adrenjTextField.getText());
        novo.setAdren(convertido);
        //novo.setInventario(inventariojTextField.getText());
        //novo.setCenario(cenariojTextField.getText());
        //novo.setEquipamento(equipamentosjTextField.getText());

        int id = 0;
        try {
            id = Integer.parseInt(idjTextField.getText());
            novo.setId(id);
            banco.alterar(novo);
        } catch (Exception erro) {
            banco.inserir(novo);
        }

        JOptionPane.showMessageDialog(
                salvarjButton, "Salvo com Sucesso!");

        cancelarjButtonActionPerformed(null);

        PersonagemTableModel modelo
                = (PersonagemTableModel) tabelajTable.getModel();

        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        idjTextField.setText("");
        nomejTextField.setText("");
        hpjTextField.setText("");
        adrenjTextField.setText("");
        equipamentosjTextField.setText("");
        inventariojTextField.setText("");
        cenariojTextField.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        // TODO add your handling code here:
        int[] linhas = tabelajTable.getSelectedRows();

        for (int i = linhas.length - 1; i >= 0; i--) {
            Personagem removido = banco
                    .getAll().get(linhas[i]);
            banco.remover(removido);

            PersonagemTableModel modelo
                    = (PersonagemTableModel) tabelajTable.getModel();

            modelo.fireTableRowsDeleted(0, 1);
        }
    }//GEN-LAST:event_removerjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        int linha = tabelajTable.getSelectedRow();

        if (linha >= 0) {
            Personagem selecionado;
            selecionado = banco.getAll().get(linha);

            idjTextField.setText(selecionado.getId() + "");
            nomejTextField.setText(selecionado.getNome());
            adrenjTextField.setText(selecionado.getAdren()+"");
            //equipamentosjTextField.setText(selecionado.getEquipamentos());
            //inventariojTextField.setText(selecionado.getInventario());
            hpjTextField.setText(selecionado.getHp()+"");
            //cenariojTextField.setText(selecionado.getc());
        } else {
            JOptionPane.showMessageDialog(this, "Selecione 1 registro");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed
                                                                                                                                                                             
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adrenjLabel;
    private javax.swing.JTextField adrenjTextField;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JLabel cenariojLabel;
    private javax.swing.JTextField cenariojTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JLabel equipamentosjLabel;
    private javax.swing.JTextField equipamentosjTextField;
    private javax.swing.JLabel hpjLabel;
    private javax.swing.JTextField hpjTextField;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel inventariojLabel;
    private javax.swing.JTextField inventariojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton removerjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
