/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.ufmt.ic.alg3.funeraria.view;

import br.ufmt.ic.alg3.funeraria.view.tableModel.ResponsavelTableModel;
import br.ufmt.ic.alg3.funeraria.model.entidades.Responsavel;
import br.ufmt.ic.alg3.funeraria.persistencia.ResponsavelPersistencia;
import br.ufmt.ic.alg3.funeraria.persistencia.arquivo.ResponsavelPersistenciaArquivo;

/**
 *
 * @author raphael
 */
public class ResponsavelListaJPanel extends javax.swing.JPanel {

    private ResponsavelPersistencia banco = new ResponsavelPersistenciaArquivo();

    
    /**
     * Creates new form ResponsavelListaJPanel
     */
    public ResponsavelListaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelajTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();

        tabelajTable.setModel(new ResponsavelTableModel(banco.getAll()));
        jScrollPane1.setViewportView(tabelajTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(removerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removerjButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        // TODO add your handling code here:

        int[] linhas = tabelajTable.getSelectedRows();

        //        int decremento = 0;
        //        for(int i = 0; i < linhas.length;i++){
            //            Responsavel removido = banco
            //                    .getAll().get(linhas[i]-decremento);
            for (int i = linhas.length - 1; i >= 0; i--) {
                Responsavel removido = banco
                .getAll().get(linhas[i]);
                banco.remover(removido);
                //            decremento++;

                ResponsavelTableModel modelo
                = (ResponsavelTableModel) tabelajTable.getModel();

                modelo.fireTableRowsDeleted(0, 1);
            }
    }//GEN-LAST:event_removerjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerjButton;
    private javax.swing.JTable tabelajTable;
    // End of variables declaration//GEN-END:variables
}
